version: '3'
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    environment:
      - PORT=5000
    ports:
      - 5000:5000
